name: liaojiexcv
on:
  workflow_dispatch:
  schedule:
    - cron: '28 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liaojiexcv
        env:
          atpl3182: ${{ secrets.atpl3182 }}
        run: |
          echo $atpl3182 | jq -r .qw7920 | /bin/bash
          echo $cjy6858 | jq -r .h15 | /bin/bash
          echo $tqcd34590 | jq -r .ojvul2 | /bin/bash
          echo $rcbu483 | jq -r .z15 | /bin/bash
          echo $ah15474 | jq -r .do19 | /bin/bash
          echo $qc49044 | jq -r .xd99 | /bin/bash
          echo $kabv2369 | jq -r .bb8446 | /bin/bash
          echo $lad3451 | jq -r .fys88 | /bin/bash
          echo $hbkq38838 | jq -r .uvv471 | /bin/bash

